### ISSUE TITLE
Repositories management tools

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#110]
Some useful repository management tools:
(Naming subject to further bike-shedding.)

- [x] `show-package`
- [x] `add-package`
- [x] `remove-package`
- [x] `edit-package`

Here are a few examples by @joelrebel:

0. List/Search pakkets

`pakket list/search [--category=<perl|python>] [--latest] <str>`

1. Add/build a new pakket

`pakket add --category=<perl|python>] [--version=latest] <str>`
    
2. Edit pakket/bag config in 

`pakket edit --category=<perl|python> <str>`

3. Fetch a pakket (for manual installs)

`pakket fetch --category=[perl|python] [--version=latest] <str>`

4. Update a pkt

`pakket update --category=[perl|python] [--version=latest] <str>`

5. Rebuild a pkt

`pakket rebuild --category=[perl|python] [--version=latest] <str>`

6. Delete a pkt

`pakket remove --category=[perl|python] [--version=latest] <str>`

7. Get info on a pkt (dump metadata - provides, requires, sha/json file info)

`pakket info --category=[perl|python] [--version=latest] <str>`

**Comment by mickeyn** [comment]
add/remove/replace source functionality already in 
https://github.com/xsawyerx/pakket/tree/mickey/repo_command

took a detour to fix broken scaffolding code in order to include its functionality to adjust the specs with the sources changes.

**Comment by mickeyn** [comment]
I think we can close this issue, we now have the following manage options:
- add package (from repo)
- remove package (from repo)
- add dependency (to package spec)
- remove dependency (from package spec)
- show package (spec)
- list packages | specs | parcels (list in format installer/builder can use)

For new functionality - lets just create a new issue.
