### ISSUE TITLE
Scaffolder needs to be updated to match repositories

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#112]
The Scaffolder is still hard-coding the concept of an index, which no longer works.

**Comment by mickeyn** [comment]
I'm guessing this is no longer relevant.
The scaffolder reads index(es) from the repo(s) and not directly.

Can we close this issue?

**Comment by mickeyn** [comment]
@xsawyerx ?

**Comment by xsawyerx** [comment]
:+1:
