### ISSUE TITLE
Clean up tools

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#113]
The following tools need to be cleaned up, and some maybe removed:

- [x] `create_pkg_index.pl`
- [x] `fetch_source.pl`
- [x] `import_sources.pl`
- [x] `import_specs.pl`
- [x] `merge_json.pl`

**Comment by mickeyn** [comment]
removed `create_pkg_index` + `merge_json` as they are tightly coupled with the old concept of index and are not used.

not sure what we need `fetch_source` for... if we needed that functionality outside of scaffolding, we can integrate it more properly into the new `repo` command - shall I remove it?

the `import_*` scripts can probably be removed as well - what do you think? (for 1-2 cases we might need to use them, we can pull them from git)

**Comment by mickeyn** [comment]
done
