### ISSUE TITLE
Classes for the build system

### ISSUE THREAD

**Issue by sn23581** [xsawyerx/pakket#12]
We should have all the build process logic saved in classes relating to the category and the build type. Building a system package with a `make` is an example. Another would be a system package build using CMake.

Perl packages can be built with [ExtUtils::MakeMaker](https://metacpan.org/pod/ExtUtils::MakeMaker) and `make`, or they can be built using [Module::Build](Module::Build) with a `Build.PL` file.

Each of these types of builds should be its own class with common methods like `prepare`, `build`, etc.

Having hooks for each would also be nice, like `post_build`.

**Comment by xsawyerx** [comment]
We now have `Pkt::Builder`.
