### ISSUE TITLE
We should be able to store the configuration of packages in different backends

### ISSUE THREAD

**Issue by sn23581** [xsawyerx/pakket#13]
Currently the configuration is stored in TOML files in the `config-dir` directory. We should allow storing these in SQL databases, in ElasticSearch, etc.

**Comment by xsawyerx** [comment]
Now that we have a ConfigReader class, additional adapters can be read. The only thing is to decide *how* to store them in that data. That's now left to the adapter to decide.

**Comment by xsawyerx** [comment]
Configuration can now be stored practically anywhere in any format.
