### ISSUE TITLE
error: No versions provided for perl/ExtUtils::MakeMaker

### ISSUE THREAD

**Issue by zprogd** [xsawyerx/pakket#178]
getting an error for any package:
$ pakket build -vvvvvv  perl/Algorithm-NaiveBayes=0.04:1 
 * Creating build dir /tmp/BUILD-bA_EHl
 * No versions provided for perl/ExtUtils::MakeMaker
No versions provided for perl/ExtUtils::MakeMaker at /home/zprog/pakket/lib/Pakket/Repository.pm line 105.

all works good if i revert 0d18b8f7fe6e7be7dde9b3e269f2a495e0b5f415

**Comment by mickeyn** [comment]
this was fixed by 076dbce02a930963aadbf79ec59ac9bee10ebd45
