### ISSUE TITLE
Dependency tree and flattened dependencies

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#72]
We should create a tree of all the dependencies before building, and we should be able to save that as part of a config and as part of the metadata installed.

We could also save a flattened version of it (or flatten the tree).

This allows us to check conflicts before building, before installing, to parallelize the build and installation processes, and avoid queries on the Repository and mirror.

**Comment by ksurent** [comment]
Isn't this a duplicate of #38 ?

**Comment by xsawyerx** [comment]
D'oh!
