### ISSUE TITLE
Use URIs for general locations in package index

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#83]
In order to support more backends, the index should use full location URIs for packages instead of the directory:

For example:

```
category => {
    package => {
        versions => {
            '1.2.0' => 'file://location/on/disk',
        }
    }
}
```

We will begin with `file://` but should allow `http://` and `git://`.

**Comment by gonzus** [comment]
I would argue that the index should be backend-agnostic. It should only refer to packages by their symbolic names, and leave any name resolution and fetching to the repository class. Even to the point where 'versions' should just be an array of valid versions for the package. Allegedly... 

To expand: you could have one repository object that knows how to get packages from the local filesystem, and another repository object that knows how to fetch packages over HTTP. The same index should work with both repository objects.

You could also give each repository class the ability to delegate to other repository objects the resolution and fetching of packages. This way you could configure a repository that delegates preferentially into a file-system-repository object, and after trying that, delegates into an HTTP-fetch-repository.

**Comment by xsawyerx** [comment]
How do you see repository objects resolve package names to their location, whether on disk or through an HTTP request?

**Comment by gonzus** [comment]
I will summarize my chat with @xsawyerx. This is an example fragment of a current index file:

```
perl => {
  Foo::Bar => {
    1.0.1 => "file:///var/pakket/packages/perl/Foo::Bar/1.0.1/..."
  }
  Foo::Baz => {
    2.3.4 => "file:///var/pakket/packages/perl/Foo::Baz/2.3.4/..."
  }
}
```

Problems I see with this:
- It mixes information about the package itself and where it could live.
- It forces to duplicate partial information about the location; in this case, "file:///var/pakket/" is duplicated for each package.
- Adding a new possible location would mean adding it to each package.

Instead, I believe the index should only contain the information about the package and its versions, and nothing about its possible locations. For example:

```
perl => {
  Foo::Bar => {
    versions => [ 1.0.1, ... ],
    latest => 2.4
  }
  Foo::Baz => {
    versions => [ 2.3.4, ... ],
    latest => 3.1
  }
}
```

So now, the information about where the packages live needs to be stored somewhere else. These would be the Fetcher classes / roles. For example:

```
FetcherFileSystem->new(directory => '/var/pakket/packages');
FetcherHTTP->new(URL => 'https://pakket.mycompany.com', base => '/pakket/packages');
```

You could even create a FetcherCombo, that aggregates a bunch of different fetchers and delegates to them in a given order, trying each one in turn:

```
FetcherCombo->new(
    FetcherFileSystem->new('/var/pakket/packages'),
    FetcherFileSystem->new('/var/lib/pakket/packages'),
    FetcherHTTP->new('https://pakket.mycompany.com/pakket/packages'),
    FetcherFailAlways('not found')
);
```

**Comment by xsawyerx** [comment]
Another comment to add to this: The only way a Fetcher is valuable is if it has a location to store something. Otherwise, what does *fetching* mean?

If we're building something, we need to fetch the source from either a remote location or a directory and put it in the build directory.

**Comment by gonzus** [comment]
Yes, it makes sense that a Fetcher would know where to put fetched packages. Unless you want to go really minimal and have Storer objects as well:

```perl
# knows how to fetch packages via HTTP from this URL
my $fetcher = FetcherHTTP->new(URL => 'https://pakket.mycompany.com', base => '/pakket/packages');
# this fetches the package and keeps it in memory
my $foobar = $fetcher->fetch('perl', 'Foo::Bar');
...
# knows how to store packages in the file system
my $storer = StoreFileSystem->new(directory => '/var/pakket/packages');
# this stores the package we just fetched
$storer->store($foobar);
```

But this would force you to have an in-memory representation of packages, and will surely use a lot of memory.

Another way is to have a set of Storage classes / roles, so that each Fetcher has one of these. So you could have:

```perl \
# when this scope is exited, $storage will delete the directory
my $storage = StorageFileSystem->new(directory => '/tmp/whatever', autoclean => 1);
my $fetcher = FetcherHTTP->new(URL => 'https://pakket.mycompany.com', base => '/pakket/packages', storage => $storage);
my $location = $fetcher->fetch('perl', 'Foo::Bar', 'latest');
# now location is something like '/tmp/whatever/perl/Foo::Bar/2.3.4'
```

Having this in a separate class / role would allow you to create StorageMySQL, StorageNapkin, etc.

**Comment by xsawyerx** [comment]
I like this idea but it might just be too far for now.

**Comment by xsawyerx** [comment]
This is resolved in the **feature/repository-backends-2** branch.

**Comment by xsawyerx** [comment]
Merged!
