### ISSUE TITLE
Remove the examples directory from history

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#90]
One thing I noticed now is that the current `examples` directory takes 34M!

I think we should remove it from the repo history. This means everyone (about 3 people) will have to create patches from every branch, delete the repo, clone it from scratch, and recreate the branch from the patches.

Any objections?
(pinging @gonzus @mickeyn)

**Comment by mickeyn** [comment]
no objection, we don't even use it - you can nuke it, or we may want to move it / an alternative example structure as a **separate repo** available for people who want to learn how to use it.

**Comment by xsawyerx** [comment]
I think a separate repo is a good idea. Friday I'm going to nuke it from the history and ask everyone to clean up any branches into patches and remove the repo and reclone.

**Comment by xsawyerx** [comment]
This is done. I believe this invalidated the existing pull requests (unless @mickeyn merged it before I noticed).

Before you continue your work:
* Create a set of patches for all of your local changes
* Delete the Pakket repo and re-clone
