### ISSUE TITLE
Should we normalize the TOML config handling?

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#98]
We're using `TOML::Parser` to parse but `TOML.pm` to serialize. `TOML.pm` has both reading and writing. Was there a reason why we opted for both? Where there things `TOML::Parser` was able to parse that `TOML.pm` could not?

**Comment by gonzus** [comment]
TOML uses TOML::Parser to parse stuff... So, I guess we could just use TOML directly.

**Comment by xsawyerx** [comment]
A problem I recall we had was a module that had a '+' in the distribution name ([Text-Tabs+Wrap](https://metacpan.org/release/Text-Tabs+Wrap)) would output a config that could then not be read. I think it's because of using these two different modules. One would create something the other couldn't read.

Now I honestly don't see a reason not to just use `TOML.pm`. @mickeyn, thoughts?

**Comment by xsawyerx** [comment]
Due to #106, we can close this ticket now as not actionable.
